# action.yml
name: "bosh-releaser"
description: "Creates new version of bosh release"

inputs:
  repository:
    description: "Github repository used to publish releases."
    required: false
    default: ${GITHUB_REPOSITORY}
  token:
    description: "Github token used to push changes after releasing"
    required: false
    default: ${GITHUB_TOKEN}
  target_branch:
    description: "Branch name to push release commit"
    required: false
    default: master
  tag_name:
    required: false
    description: "Tag name used to create the bosh release. Leave it empty to autodetect"
  override_existing:
    description: "override existing tag or release"
    required: false
    default: false
  dir:
    description: "Release directory path if not current working directory (default: .)"
    default: "."
  debug:
    description: "Set to 1 to enable debug mode"
    default: 0
outputs:
  file:
    description: "generated bosh release filename"
  version:
    description: "version of the generated bosh release"

runs:
  using: "docker"
  image: "Dockerfile" # We should be able to use this action without explict commit using 'orangecloudfoundry/create-bosh-release-action@master'
