name: build-and-release

on:
  push:
    # not consider simple commit
    branches:
      - '!*'
    # consider only release and pre-release tags
    tags:
      - 'v[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute docker tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5
        with:
          images: orangecloudfoundry/create-bosh-release-action

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to DockerHub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
