name: on-commit

on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ./create-bosh-release-action
      - name: Checkout repository test repo
        id: checkout_test_repo
        uses: actions/checkout@v4
        with:
          repository: 'orange-cloudfoundry/create-bosh-release-action-test-boshrelease'
          fetch-depth: 0
#          ref: v1.0
#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./create-bosh-release-action-test-boshrelease

#      - name: Setup tests
#        id: setup_tests
#        run: |
#          du -a
#          git config --global --add safe.directory /github/workspace/create-bosh-release-action-test-boshrelease
#          git --no-pager config --global --list

      - name: Test dev release
        id: test_dev_release
        uses: ./create-bosh-release-action/ # uses: ./.github/actions/my-private-repo/my-action #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow
        with:
          target_branch: main
          dir: create-bosh-release-action-test-boshrelease
      - name: Generated test files status
        run: |
          ls -lrt
          cd create-bosh-release-action-test-boshrelease
          git status
          #echo "Cleanup generated files"
          #git clean -fdx
          cd ..
      - name: Test final release
        id: test_final_release
        uses: ./create-bosh-release-action/ # uses: ./.github/actions/my-private-repo/my-action #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow
        with:
          repository: orange-cloudfoundry/create-bosh-release-action-test-boshrelease
          target_branch: main
          dir: create-bosh-release-action-test-boshrelease
          tag_name: "0.1.0"
          override_existing: "true"
          debug: 1