name: Renovate

on:
  schedule:
    - cron: '3 5 * * 6'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          docker-user: root
          configurationFile: .github/renovate.json
          token: ${{ secrets.PAASBOT_TOKEN }}
